version: "3.8"
services:
  database:
    image: "bitnami/mongodb:latest"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=user
      - MONGODB_ROOT_PASSWORD=hello
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - "27017:27017"
    volumes:
      - "mongo-db:/bitnami/mongodb"

volumes:
  mongo-db: